# Generated by Django 6.0.2 on 2026-02-28 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_public"], name="habits_habi_user_id_175c9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["time"], name="habits_habi_time_781a31_idx"),
        ),
    ]
